// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hey.dou.Models;

#nullable disable

namespace hey.dou.Migrations
{
    [DbContext(typeof(HeydouContext))]
    [Migration("20251031191457_RenkKoduManuelEkle")]
    partial class RenkKoduManuelEkle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hey.dou.Models.AkademikTakvim", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EventID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("BaslangicTarihi")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BitisTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Kategori")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RenkKodu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId")
                        .HasName("PK__Akademik__7944C870C6B6AF77");

                    b.ToTable("AkademikTakvim", (string)null);
                });

            modelBuilder.Entity("hey.dou.Models.HaftalikMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MenuID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("AnaYemek")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Corba")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gun")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.Property<string>("TatliVeyaMeyve")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("YardimciYemek")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MenuId")
                        .HasName("PK__Haftalik__C99ED250A7367CF7");

                    b.ToTable("HaftalikMenu", (string)null);
                });

            modelBuilder.Entity("hey.dou.Models.SelamBacılar", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Veri")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("veri");

                    b.HasKey("Id")
                        .HasName("PK__selamBAc__3213E83FAD7153AF");

                    b.ToTable("selamBAcılar", (string)null);
                });

            modelBuilder.Entity("hey.dou.Models.TestTablosu", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Mesaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("TestTablosu", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
