// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hey.dou.Models;

#nullable disable

namespace hey.dou.Migrations
{
    [DbContext(typeof(HeydouContext))]
    [Migration("20251123200349_CreatorKullaniciKolonu")]
    partial class CreatorKullaniciKolonu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeyDou.Models.StajIlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aciklama");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("aktif");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("baslik");

                    b.Property<string>("BasvuruLinki")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("basvuru_linki");

                    b.Property<string>("Lokasyon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lokasyon");

                    b.Property<string>("Sirket")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sirket");

                    b.Property<DateTime?>("SonBasvuru")
                        .HasColumnType("datetime2")
                        .HasColumnName("son_basvuru");

                    b.Property<string>("StajTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("staj_turu");

                    b.Property<DateTime>("YayinlanmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("yayinlanma_tarihi");

                    b.HasKey("Id");

                    b.ToTable("staj_ilanlari");
                });

            modelBuilder.Entity("hey.dou.Models.AkademikTakvim", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EventID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("BaslangicTarihi")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BitisTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Kategori")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RenkKodu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId")
                        .HasName("PK__Akademik__7944C870C6B6AF77");

                    b.ToTable("AkademikTakvim", (string)null);
                });

            modelBuilder.Entity("hey.dou.Models.Anket", b =>
                {
                    b.Property<int>("AnketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnketId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnketId");

                    b.ToTable("Ankets");
                });

            modelBuilder.Entity("hey.dou.Models.AnketSecenegi", b =>
                {
                    b.Property<int>("SecenekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecenekId"));

                    b.Property<int>("AnketId")
                        .HasColumnType("int");

                    b.Property<string>("CreatorKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecenekText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SecenekId");

                    b.HasIndex("AnketId");

                    b.ToTable("AnketSecenegis");
                });

            modelBuilder.Entity("hey.dou.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int?>("AnketId")
                        .HasColumnType("int");

                    b.Property<bool>("AnketSonucuSecildi")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("KatilimOylamasiAcik")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.HasIndex("AnketId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("hey.dou.Models.HaftalikMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MenuID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("AnaYemek")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Corba")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gun")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.Property<string>("TatliVeyaMeyve")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("YardimciYemek")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MenuId")
                        .HasName("PK__Haftalik__C99ED250A7367CF7");

                    b.ToTable("HaftalikMenu", (string)null);
                });

            modelBuilder.Entity("hey.dou.Models.Katilim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EtkinlikId")
                        .HasColumnType("int");

                    b.Property<bool>("KatilimDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EtkinlikId", "KullaniciId")
                        .IsUnique();

                    b.ToTable("Katilimlar");
                });

            modelBuilder.Entity("hey.dou.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("hey.dou.Models.Oy", b =>
                {
                    b.Property<int>("OyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OyId"));

                    b.Property<int>("AnketId")
                        .HasColumnType("int")
                        .HasColumnName("AnketID");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserID");

                    b.Property<int>("SecenekId")
                        .HasColumnType("int")
                        .HasColumnName("SecenekID");

                    b.HasKey("OyId");

                    b.HasIndex("SecenekId");

                    b.HasIndex("AnketId", "KullaniciId")
                        .IsUnique();

                    b.ToTable("Oys");
                });

            modelBuilder.Entity("hey.dou.Models.SelamBacılar", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Veri")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("veri");

                    b.HasKey("Id")
                        .HasName("PK__selamBAc__3213E83FAD7153AF");

                    b.ToTable("selamBAcılar", (string)null);
                });

            modelBuilder.Entity("hey.dou.Models.TestTablosu", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Mesaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("TestTablosu", (string)null);
                });

            modelBuilder.Entity("hey.dou.Models.AnketSecenegi", b =>
                {
                    b.HasOne("hey.dou.Models.Anket", "Anket")
                        .WithMany("AnketSecenegis")
                        .HasForeignKey("AnketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anket");
                });

            modelBuilder.Entity("hey.dou.Models.Event", b =>
                {
                    b.HasOne("hey.dou.Models.Anket", "Anket")
                        .WithMany()
                        .HasForeignKey("AnketId");

                    b.Navigation("Anket");
                });

            modelBuilder.Entity("hey.dou.Models.Katilim", b =>
                {
                    b.HasOne("hey.dou.Models.Event", "Etkinlik")
                        .WithMany("Katilimlar")
                        .HasForeignKey("EtkinlikId")
                        .IsRequired()
                        .HasConstraintName("FK_Katilim_Event");

                    b.Navigation("Etkinlik");
                });

            modelBuilder.Entity("hey.dou.Models.Oy", b =>
                {
                    b.HasOne("hey.dou.Models.Anket", "Anket")
                        .WithMany("Oys")
                        .HasForeignKey("AnketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hey.dou.Models.AnketSecenegi", "AnketSecenegi")
                        .WithMany("Oys")
                        .HasForeignKey("SecenekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anket");

                    b.Navigation("AnketSecenegi");
                });

            modelBuilder.Entity("hey.dou.Models.Anket", b =>
                {
                    b.Navigation("AnketSecenegis");

                    b.Navigation("Oys");
                });

            modelBuilder.Entity("hey.dou.Models.AnketSecenegi", b =>
                {
                    b.Navigation("Oys");
                });

            modelBuilder.Entity("hey.dou.Models.Event", b =>
                {
                    b.Navigation("Katilimlar");
                });
#pragma warning restore 612, 618
        }
    }
}
